### ISSUE TITLE
Allow upload of large WhiteRabbit Scan reports

### ISSUE THREAD

**Issue by PhilAppleby** [Health-Informatics-UoN/CaRROT-Mapper#612]
The upload function times-out for large scan reports.

For example, for the UoD SHARE dataset - more detail will be supplied in comments

**Comment by spco** [comment]
More definition/examples of "large" are required. #tables, #fields, #values, #reused mappings, or #vocab-mapped values. All of these should ideally be handled by CaRROT-Mapper, but examples are needing for testing.

**Comment by AndyRae** [comment]
I think there are 3 things we can do here:

1. As discussed, separate out the creation of tables function from the processing, and processing is only triggered after the user has set their ID / date in the web app. I'm unsure how much time this will save, but it will help with making the code more robust, and make the UX workflow clearer. I've begun work on looking at this.
2. Use the database directly instead of the Django API - looking through, I don't think this would be much work. We would move the tables to a shared library in the code, and enable the functions to use it instead. 
3. Increase the timeout on the function - this depends on the plan.

**Comment by AndyRae** [comment]
As discussed, we're continuing with our work to split out the Scan Report fields "upload" from the Concept "processing". 
Our first iteration of this to come soon will continue with the existing UI, but the Scan Report will be uploaded in the UI, with no processing taking place. We will then create Concepts per table (and get the reusable Concepts) when the user selects their "Person ID" and "Date Event" for the table, and selects: "Update Table".

After that, we can either put effort into:
1. Make this upload and processing faster, directly using the Django ORM rather than the REST API.
2. Design the UX into a multi step form to support uploading a Scan Report. Currently our outlined temporary UX means still having to traverse the UI to upload, select their table details and so on. Ideally we want this encapsulated into a supported form to guide the user through, with the option for #623 also. And then allow for viewing more detailed logs and status of the upload/process.
