### ISSUE TITLE
Mapping Rule generation fails for large White Rabbit Scan reports

### ISSUE THREAD

**Issue by PhilAppleby** [Health-Informatics-UoN/CaRROT-Mapper#616]
Timeout occurs for large scan reports, meaning manual intervention is necessary.

Examples in comments

**Comment by spco** [comment]
This is being tackled by moving this task to an Azure Function. If we implement the setting of PersonID and Date Event from the Data Dictionary, then this would all happen at the time of upload rather than once all Person IDs and Date Events are set, removing a confusing and at times painful process for users.
