### ISSUE TITLE
🐛 CSV rules output needs a further change

### ISSUE THREAD

**Issue by PhilAppleby** [Health-Informatics-UoN/CaRROT-Mapper#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new format for csv output has introduced an error - the 'domain' column contains target field and domain is not present in the output records.

### Expected Behavior

The domain column should contain OMOP domain and OMOP target field should be present in a 'target_field' column which will have to be added / re-instated

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by spco** [comment]
Yup - this is due to #653. In that, `destination_field` has been incorrectly used for `domain` information. It should be using `destination_table` instead. `destination_field` needs to returned under its own heading (this is the euaivalen tof `target_table` above).

This doesn't affect the rendering of the rules webpage, but is also confusing for the future there.
